# Generated by Django 2.1.7 on 2019-03-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190302_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='person',
        ),
        migrations.DeleteModel(
            name='Pill',
        ),
    ]
