# Generated by Django 2.1.7 on 2019-03-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190302_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profilePic',
        ),
    ]
