# Generated by Django 2.1.7 on 2019-03-02 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_n', models.CharField(max_length=200)),
                ('last_n', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profilePic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pill_text', models.CharField(max_length=500)),
                ('startDay', models.DateField(default=datetime.date.today)),
                ('remindTimes', models.TimeField()),
                ('endDay', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.Person')),
            ],
        ),
    ]
